CREATE TABLE conversations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_conversations PRIMARY KEY (id)
);

CREATE TABLE conversation_participants
(
    conversation_id BIGINT NOT NULL,
    user_id         UUID   NOT NULL,
    CONSTRAINT pk_conversation_participants PRIMARY KEY (conversation_id, user_id),
    CONSTRAINT fk_conpar_on_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id),
    CONSTRAINT fk_conpar_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);

ALTER TABLE messages
    DROP COLUMN IF EXISTS author_login;
ALTER TABLE messages
    DROP COLUMN IF EXISTS version;

ALTER TABLE messages
    DROP CONSTRAINT IF EXISTS messages_pkey;
ALTER TABLE messages
    DROP COLUMN IF EXISTS id;

ALTER TABLE messages
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

ALTER TABLE messages
    ADD COLUMN sender_id UUID;
ALTER TABLE messages
    ADD COLUMN conversation_id BIGINT;

ALTER TABLE messages
    ALTER COLUMN sender_id SET NOT NULL;
ALTER TABLE messages
    ALTER COLUMN conversation_id SET NOT NULL;

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id);
ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES conversations (id);
