drop table if exists device cascade;
create table device (
    area float(53),
    max_power_per_hour integer,
    min_wind_speed_for_max_power integer,
    total_consumed numeric(38,2),
    total_generated numeric(38,2),
    working boolean,
    id uuid generated by default as identity,
    type varchar(31) not null,
    description varchar(255),
    primary key (id)
                    );
