spring.application.name=server
spring.datasource.url=jdbc:postgresql://localhost:5434/IO_db
spring.datasource.username=iouser
spring.datasource.password=1234
server.error.include-message=always
jwt.secret=DSSVeORkCWxrgIjkvKs1ZzNjW1eMTreu6kVNV0yM021LWqfWZqyTIeRSalDJPkbc
jwt.expiration.access=900000 
jwt.expiration.refresh=604800000

#xdddd
spring.mail.host=smtp.wp.pl
spring.mail.port=465
spring.mail.username=ioias@wp.pl
spring.mail.password=@Dmin1234
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true