spring.application.name=server
spring.datasource.url=jdbc:postgresql://localhost:5434/IO_db
spring.datasource.username=iouser
spring.datasource.password=1234
server.error.include-message=always
jwt.secret=DSSVeORkCWxrgIjkvKs1ZzNjW1eMTreu6kVNV0yM021LWqfWZqyTIeRSalDJPkbc
jwt.expiration.access=900000 
jwt.expiration.refresh=604800000
spring.flyway.clean-disabled=false