### Pobierz wszystkie wiadomości
GET http://localhost:8080/api/communication/messages
Accept: application/json

### Utwórz nową wiadomość
POST http://localhost:8080/api/communication/messages
Content-Type: application/json

{
  "content": "To jest przykładowa wiadomość.",
  "authorLogin": "hardstyl3r"
}

### Utwórz nowego rezydenta
POST http://localhost:8080/users/residents
Content-Type: application/json

{
  "login": "hardstyl3r",
  "password": "1234",
  "firstName": "Aleksander",
  "lastName": "Gencel",
  "active": true,
  "email": "thank@you.pl",
  "room": "101A"
}
